name: Check Deploy Label

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  check-deploy-libs:
    name: Validate Deploy Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check Labels
        id: check-labels
        run: |

          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
        
          labels=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
            | jq -r '.labels // [] | map(.name)')

          echo "Pull request labels: $labels"

          filteredLabels=$(echo "$labels" | jq -r 'map(select(startswith("Deploy - ")))')

          echo "Deploy labels: $filteredLabels"

          deployIsValid=true

          if [ "$filteredLabels" == "[]" ]; then
            echo "No deploy label selected."
            deployIsValid=false
          elif [ $(echo "$filteredLabels" | jq length) -gt 1 ]; then
            echo "More than one deploy label selected."
            deployIsValid=false
          fi

          echo "deployIsValid=$deployIsValid" >> $GITHUB_ENV
