name: Check Deploy Label

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  check-deploy-libs:
    name: Validate Deploy Labels
    runs-on: ubuntu-latest
    steps:
      - name: Check Labels
        uses: actions/github-script@v7
        with:
          script:
            const labels = context.payload.pull_request.labels.map(label => label.name);
            console.log("labels:", labels);
