name: Check Deploy Label

on:
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]

jobs:
  check-deploy-libs:
    name: Validate Deploy Labels
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Analyse Labels
        id: get-labels
        run: |

          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}
        
          labels=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
            | jq -r '.labels // [] | map(.name)')

          echo "Pull request labels: $labels"

          filteredLabels=$( $labels | jq -r 'map(select(startswith("Deploy - ")))')

          echo "Deploy labels: $filteredLabels"          
