name: Trigger Deploy TestEnum

on:
  push:
    branches:
      - main
    paths:
      - "TestEnum/*"

jobs:
  trigger-deploy:
      name: Call Deploy Java Packages Workflow
      uses: ./.github/workflows/package.yml
      with:
        package: 'TestEnum'
        java_version: '21'
        java_distribution: 'zulu'
      permissions:
        contents: read
        packages: write