name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Get Updated API
        run: |
          lib=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
            | jq -r '.labels // [] | map(.name)' \
            | 'map(select(startswith("Deploy - ")))' \
            | '.[0]' \
            | sed 's/^Deploy - //')
          echo "lib=$lib" >> $GITHUB_ENV
      - name: Publish package
        run: |
          cd ./$lib
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
