name: Publish package to GitHub Packages
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Get Updated API
        run: |

          PR_NUMBER=${{ github.event.pull_request.number }}
          REPO=${{ github.repository }}
          TOKEN=${{ secrets.GITHUB_TOKEN }}

          labels=$(curl -s -H "Authorization: token $TOKEN" \
            "https://api.github.com/repos/$REPO/pulls/$PR_NUMBER" \
            | jq -r '.labels // [] | map(.name)')
        
          filteredLabels=$(echo "$labels" | jq -r 'map(select(startswith("Deploy - ")))')

          lib=$(echo "$filteredLabels" | jq -r '.[0]' | sed 's/^Deploy - //')
          
          echo "lib=$lib" >> $GITHUB_ENV
          
      - name: Publish package
        run: |
          cd ./$lib
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
